// <auto-generated />
using System;
using AspProject1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspProject1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspProject1.Models.Araclar", b =>
                {
                    b.Property<int>("AracID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AracID"));

                    b.Property<string>("BakimNotu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("AracID");

                    b.ToTable("Araclar");
                });

            modelBuilder.Entity("AspProject1.Models.BakimFiyatlari", b =>
                {
                    b.Property<int>("BakimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BakimID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BakimAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BakimID");

                    b.ToTable("BakimFiyatlari");

                    b.HasData(
                        new
                        {
                            BakimID = 1,
                            BakimAdi = "Yağ Değişimi",
                            Ucret = 500m
                        },
                        new
                        {
                            BakimID = 2,
                            BakimAdi = "Buji Değişimi",
                            Ucret = 300m
                        });
                });

            modelBuilder.Entity("AspProject1.Models.Islemler", b =>
                {
                    b.Property<int>("IslemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IslemID"));

                    b.Property<int>("AracID")
                        .HasColumnType("int");

                    b.Property<int?>("AraclarAracID")
                        .HasColumnType("int");

                    b.Property<int>("BakimID")
                        .HasColumnType("int");

                    b.Property<string>("IslemNotu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("IslemID");

                    b.HasIndex("AracID");

                    b.HasIndex("AraclarAracID");

                    b.HasIndex("BakimID");

                    b.ToTable("Islemler");
                });

            modelBuilder.Entity("AspProject1.Models.Kisiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kisiler");
                });

            modelBuilder.Entity("AspProject1.Models.Islemler", b =>
                {
                    b.HasOne("AspProject1.Models.Araclar", "Arac")
                        .WithMany()
                        .HasForeignKey("AracID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspProject1.Models.Araclar", null)
                        .WithMany("Islemler")
                        .HasForeignKey("AraclarAracID");

                    b.HasOne("AspProject1.Models.BakimFiyatlari", "BakimFiyat")
                        .WithMany()
                        .HasForeignKey("BakimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");

                    b.Navigation("BakimFiyat");
                });

            modelBuilder.Entity("AspProject1.Models.Araclar", b =>
                {
                    b.Navigation("Islemler");
                });
#pragma warning restore 612, 618
        }
    }
}
